# Generated by Django 4.1.7 on 2023-04-01 14:07

import apps.analitycs.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.analitycs.models.upload_location, validators=[apps.analitycs.models.validate_file_extension])),
                ('filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_status', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(choices=[('activity', 'Activity'), ('user', 'User'), ('lesson', 'Lesson')], default='activity', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
