version: "3"

services:
  db:
    container_name: lenglish_db
    image: postgres:13.4
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - lenglish-network

  redis:
    container_name: lenglish_redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - lenglish-network

  web:
    container_name: lenglish_web
    build: .
    volumes:
      - .:/code
      - ./static-root:/static-root
      - ./media-root:/media-root
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      # - mailhog
    image: lenglish-image
    networks:
      - lenglish-network

  celery:
    image: lenglish-image
    container_name: lenglish_celery
    command: sh -c "celery -A lenglish worker -l info"
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - lenglish-network

  # celery-beat:
  #   image: lenglish-image
  #   container_name: lenglish_celery_beat
  #   command: sh -c "celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
  #   volumes:
  #     - .:/code
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #     - redis
  #     - mailhog
  #   networks:
  #     - lenglish-network

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
  #   networks:
  #     - lenglish-network

networks:
  lenglish-network:
    driver: bridge

volumes:
  data: