# Generated by Django 4.1.7 on 2023-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_interest_users'),
        ('learning', '0003_lessonrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='interests',
            field=models.ManyToManyField(related_name='lessons', to='authentication.interest'),
        ),
    ]
