# Generated by Django 4.1.7 on 2023-03-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_useractivity_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[(1, 'Conversation'), (2, 'Grammar'), (3, 'Vocabulary'), (4, 'Word Reinforcement')], default=0, max_length=100),
        ),
    ]
