# Generated by Django 4.1.7 on 2023-03-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('0', 'Conversation'), ('1', 'Grammar'), ('2', 'Vocabulary'), ('3', 'Word Reinforcement')], default='0', max_length=1),
        ),
    ]
