# Generated by Django 4.1.7 on 2023-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
