# Generated by Django 4.1.7 on 2023-03-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_rename_description_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprogress',
            name='next_lesson_type',
            field=models.CharField(choices=[('0', 'Conversation'), ('1', 'Grammar'), ('2', 'Vocabulary'), ('3', 'Word Reinforcement')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='UserActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learning.useractivity')),
            ],
        ),
    ]
