# Generated by Django 4.1.7 on 2023-03-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_activityprogress_next_lesson_type_useractivityrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprogress',
            name='next_lesson_type',
            field=models.CharField(blank=True, choices=[('0', 'Conversation'), ('1', 'Grammar'), ('2', 'Vocabulary'), ('3', 'Word Reinforcement')], max_length=1, null=True),
        ),
    ]
