# Generated by Django 4.1.7 on 2023-03-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
