# Generated by Django 4.1.7 on 2023-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_interest_translation'),
        ('learning', '0013_activityprogress_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='authentication.interest'),
        ),
    ]
