# Generated by Django 4.1.7 on 2023-03-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_lesson_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.lesson'),
        ),
    ]
