# Generated by Django 4.1.7 on 2023-03-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_activityprogress_next_lesson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='title',
            field=models.CharField(default='My daily', max_length=150),
            preserve_default=False,
        ),
    ]
