# Generated by Django 4.1.7 on 2023-03-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_useractivitylike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityprogress',
            name='next_lesson_type',
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_lesson', to='learning.lesson'),
        ),
    ]
