# Generated by Django 4.1.7 on 2023-03-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_remove_activityprogress_next_lesson_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityprogress',
            name='is_completed',
        ),
    ]
