# Generated by Django 4.1.7 on 2023-03-27 18:42

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_remove_activityprogress_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
