# Generated by Django 4.1.7 on 2023-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_question_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrating',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
