# Generated by Django 4.1.7 on 2023-03-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_lessonrating_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user_activity_type',
            field=models.CharField(choices=[('0', 'Daily'), ('1', 'User Created'), ('2', 'User Joined'), ('3', 'User Repeated')], default='0', max_length=1),
        ),
    ]
