# Generated by Django 4.1.7 on 2023-03-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_timelineitem_item'),
        ('learning', '0027_useractivity_user_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='learning.lesson')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_timeline', to='authentication.timelineitem')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='learning.useractivity')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='authentication.timelineitem')),
            ],
        ),
    ]
