# Generated by Django 4.1.7 on 2023-03-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_lessontimeline_activitytimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.useractivity'),
        ),
    ]
