# Generated by Django 4.1.7 on 2023-04-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_useractivity_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('0', 'Conversation'), ('1', 'Grammar'), ('2', 'Word Reinforcement'), ('3', 'Quiz'), ('4', 'Story')], default='0', max_length=1),
        ),
    ]
