# Generated by Django 4.1.7 on 2023-03-24 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
