# Generated by Django 4.1.7 on 2023-03-24 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0004_remove_profile_interests_interest_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
