# Generated by Django 4.1.7 on 2023-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_timelineitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='action',
            field=models.CharField(choices=[('0', 'daily_activity_completed'), ('1', 'single_lesson_completed'), ('2', 'custom_activity_completed')], default='0', max_length=100),
        ),
    ]
